apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
  namespace: default
type: Opaque
data:
  MONGO_URI: ""
  RAZORPAY_KEY_ID: ""
  RAZORPAY_KEY_SECRET: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
